#!/bin/sh

filename=$1

if [ x"$filename" = "x" ]; then
    echo "Usage: $(basename $0) <filename>"
    echo "    -- Copy guest '$share_dir/<filename>' to local directory"
    exit 1
fi

. $(dirname $0)/system.conf

echo "#1# check '$filename' in guest $share_dir/"
$ssh_run_base ls -l $share_dir/$filename

echo "#2# start copy..."
$ssh_scp_base $guest_address:$share_dir/$filename .

echo "#3# check '$filename' in current directory"
ls -l ./$filename
