scripts_dir="$(realpath $(dirname $0))"
buildroot_dir="$(realpath $(dirname $0)/../../../)"

#echo "in system.config: buildroot_dir=$buildroot_dir, scripts_dir=$scripts_dir"

#1. qemu
qemu_dir="$topdir/software/qemu"
qemu_system_bin="qemu-system-aarch64"

#2. compiler
cross_compile="$buildroot_dir/output/host/usr/bin/arm-linux-"
cross_gcc="$buildroot_dir/output/host/usr/bin/arm-linux-gcc"
cross_gdb="$buildroot_dir/output/host/usr/bin/arm-linux-gdb"
host_gcc="gcc"

#3. linux
if [ -f "$buildroot_dir/.config" ]; then
    linux_version=$(grep BR2_LINUX_KERNEL_VERSION $buildroot_dir/.config | cut -d '"' -f2)
fi
linux_dir="$buildroot_dir/output/build/linux-$linux_version"
linux_kernel="$buildroot_dir/output/images/Image"
linux_rootfs="$buildroot_dir/output/images/rootfs.ext2"
linux_dtb="$buildroot_dir/output/images/vexpress-v2p-ca9.dtb"

#4. u-boot
uboot_image="$buildroot_dir/output/images/u-boot"
uboot_sd="$linux_rootfs"

#5. app

#6. drivers

#7. guest
guest_ip="10.0.2.15"
guest_address="root@$guest_ip"
guest_passwd="123"
share_dir=/root

#8. ssh
ssh_sshpass="sshpass"
ssh_run_base="$ssh_sshpass -p $guest_passwd ssh -o LogLevel=quiet -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $guest_address"
ssh_scp_base="$ssh_sshpass -p $guest_passwd scp -o LogLevel=quiet -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r"

